DecDet/api/urls.py
from django.urls import path
from .views import DecDetListAPIView, DecDetCreateAPIView, DecDetDetailAPIView


app_name = 'api-decdet'


urlpatterns = [

    path('list/', DecDetListAPIView.as_view(), name = 'list'),
    path('detail/', DecDetDetailAPIView.as_view(), name = 'detail'),
    path('create/', DecDetCreateAPIView.as_view(), name = 'create')

]

DecDet/urls.py
from django.urls import path, include

from .views import DecDetListView, DecDetCreateView, DecDetDetailView, DecDetUpdateView, DecDetDeleteView

app_name = 'DecDet'

urlpatterns = [
    path('list/', DecDetListView.as_view(), name = 'list'),
    path('create/', DecDetCreateView.as_view(), name = 'create'),
    path('<int:pk>', DecDetDetailView.as_view(), name = 'detail'),
    path('delete/<int:pk>', DecDetDeleteView.as_view(), name = 'delete'),
    path('update/<int:pk>', DecDetUpdateView.as_view(), name = 'update'),

    path('api/', include('DecDet.api.urls', namespace = 'api-decdet')),

]

ssac/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from .views import DashBoardView, SSACView

urlpatterns = [
    path('', SSACView.as_view(), name = 'Bienvenue'),
    path('accueil/', DashBoardView.as_view(), name = 'home'),
    path('decdet/', include('DecDet.urls', namespace = 'decdet')),
    path('article/', include('Article.urls', namespace = 'article')),
    path('transfert/', include('Transfert.urls', namespace='transfert')),
    path('prorogation/', include('Prorogation.urls', namespace='prorogation')),
    path('appurement/', include('Appurement.urls', namespace='appurement')),


    path('admin/', admin.site.urls, name = 'admin'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('accounts/', include('django.contrib.auth.urls'))

]

DecDet/models.py
from django.db import models
from django.urls import reverse_lazy

import datetime



class DecDetManager(models.Manager):

    def getListUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:list')

    def getCreateUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:create')

    def getUpdateUrl(self, decdet, **kwargs):
        return decdet.getUpdateUrl()

    def getDetailUrl(self, decdet, **kwargs):
        return decdet.getUpdateUrl()

    def getApiListUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:api-decdet:list')

    def getApiCreateUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:api-decdet:create')

    def getApiDetailUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:api-decdet:detail')

    def create_decdet(self, decdet_args, *args, **kwargs):
        try:
            new_decdet = self.model(
                code            = decdet_args['code'],
                num_decdet      = decdet_args['num_decdet'],
                importateur     = decdet_args['importateur'],
                declarant       = decdet_args['declarant'],
                val_marchandise = decdet_args['val_marchandise'],
                taux_suspension = decdet_args['taux_suspension'],
                montant_dit     = decdet_args['montant_dit'],
                numero_caution  = decdet_args['numero_caution'],
                date_caution    = decdet_args['date_caution'],
                num_contrat     = decdet_args['num_contrat'],
                objet_contrat   = decdet_args['objet_contrat'],
                lieu_execution  = decdet_args['lieu_execution'],
                duree_contrat   = decdet_args['duree_contrat'],
                num_autors_at   = decdet_args['num_autors_at'],
                date_autors_at  = decdet_args['date_autors_at'],
                duree_decdet    = decdet_args['duree_decdet']
            )
            new_decdet.save()

        except Exception as e:
            new_decdet = None
        return new_decdet


class DecDetModel(models.Model):
    """docstring for DecDetModel."""

    class Meta:
        verbose_name_plural = 'Déclarations en Détail'


    code            = models.CharField(max_length = 4, default='')
    num_decdet      = models.CharField(max_length = 255, default='', unique = True)
    importateur     = models.CharField(max_length = 255, default='')
    declarant       = models.CharField(max_length = 255, default='')
    val_marchandise = models.PositiveIntegerField(default=0)
    taux_suspension = models.PositiveIntegerField(default=0)
    montant_dit     = models.PositiveIntegerField(default=0)


    numero_caution  = models.CharField(max_length = 255, default='')
    date_caution    = models.DateField(default=datetime.date.today)

    num_contrat     = models.CharField(max_length = 255, default='')
    objet_contrat   = models.CharField(max_length = 255, default='')
    lieu_execution  = models.CharField(max_length = 255, default='')
    duree_contrat   = models.PositiveIntegerField(default=0)

    num_autors_at   = models.CharField(max_length = 255, default='')
    date_autors_at  = models.DateField(default=datetime.date.today)
    duree_decdet    = models.PositiveIntegerField(default=0)


    timestamp       = models.DateTimeField(auto_now_add=True, blank=True)# date of creation

    objects         = DecDetManager()

    def __str__(self):
        return "Admission Temporaire n°"+str(self.num_decdet)

    def get_absolute_url(self):
        return self.getDetailUrl()

    def getUpdateUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:update', kwargs={"pk":self.pk})

    def getDetailUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:detail', kwargs={"pk":self.pk})

    def getDeleteUrl(self, *args, **kwargs):
        return reverse_lazy('decdet:delete', kwargs={"pk":self.pk})

    def getArticleListApiUrl(self, *args, **kwargs):
        return reverse_lazy('article:api-article:decdet', kwargs={'decdet_pk' : self.pk})

    # def getProrogationApiCreateUrl(self, *args, **kwargs):
    #     return reverse_lazy('prorogation:api-prorogation:create', kwargs={'decdet_pk' : self.pk})

    def getAppurementApiCreateUrl(self, *args, **kwargs):
        return reverse_lazy('article:api-article:appurer')

    def getAppurementListUrl(self, *args, **kwargs):
        return reverse_lazy('appurement:decdet-list', kwargs={'decdet_pk' : self.pk})

    def getProrogationListUrl(self, *args, **kwargs):
        return reverse_lazy('prorogation:list', kwargs={'pk' : self.pk})

    def getTransfertsListUrl(self, *args, **kwargs):
        return reverse_lazy('transfert:decdet-list', kwargs={'pk' : self.pk})

    def getPriceAppure(self, *args, **kwargs):
        price = self.article_set.filter(appure = True).aggregate(models.Sum('valeur'))
        return price

    def getPriceTotal(self, *args, **kwargs):
        price = self.article_set.all().aggregate(models.Sum('valeur'))
        return price

    def getProrogationApiListUrl(self):
        return reverse_lazy('prorogation:api-prorogation:list', kwargs={'decdet_pk' : self.pk})


    def getDecdetStatus(self):
        status_appurement = ''
        nbPending = nbRetard = 0
        article_set = self.article_set.all()

        for article in article_set:
            article_status = article.getStatusAppurement()
            if article_status == 'retard':
                nbRetard+=1
            elif article_status == 'pending':
                nbPending+=1

        if nbRetard == len(article_set):
            status_appurement = 'retard'
        elif nbRetard !=0:
            status_appurement = 'pending-retard'
        elif nbPending !=0:
            status_appurement = 'pending'
        else:
            status_appurement = 'appure'
        return status_appurement

    def get_nb_articles_statut_retard(self):
        article_set = self.article_set.all()
        nbRetard = 0
        for article in article_set:
            article_status = article.getStatusAppurement()
            if article_status == 'retard':
                nbRetard+=1
        return nbRetard

    def getDeltaAppurement(self):
        decdet = self
        delta_appurement = (decdet.date_autors_at + datetime.timedelta(days=30)*decdet.duree_decdet) - datetime.datetime.now().date()
        return int(delta_appurement.days / 30)

    def getDureeTransfertMax(self):
        decdet = self
        delta_appurement = (decdet.date_autors_at + datetime.timedelta(days=30)*decdet.duree_decdet) - datetime.datetime.now().date()
        return int(delta_appurement.days / 30)


    @classmethod
    def getCreateUrl(self, *args, **kwargs):
        return self.objects.getCreateUrl()
    @classmethod
    def getListUrl(self, *args, **kwargs):
        return self.objects.getListUrl()

DecDet/forms.py
import datetime
from django import forms
from ssac.forms import DateInput

from .models import DecDetModel

class DecDetCreateForm(forms.ModelForm):
    class Meta:
        model   = DecDetModel
        fields = '__all__'
        labels = {
        'num_decdet' : 'N° Déclaration',
        'declarant' : 'Déclarant',
        'val_marchandise' : 'Valeur Marchandise',
        'taux_suspension' : 'Taux de suspension',
        'montant_dit' : 'Montant D/T',
        'numero_caution' : 'N° Caution',
        'num_contrat' : 'N° Contrat',
        'lieu_execution' : 'Lieu d\'exécution',
        'duree_contrat' : 'Durée du contrat',
        'num_autors_at' : 'N° Autorisation d\'admission',
        'date_autors_at' : 'Date Autorisation d\'admission',
        'duree_decdet' : 'Durée accordée',
        }
        widgets = {
        'date_caution' : DateInput(format='%Y-%m-%d'),
        'date_autors_at' : DateInput(format='%Y-%m-%d')
        }

DecDet/api/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404

from rest_framework import generics, permissions
from rest_framework.views import APIView
from rest_framework.response import Response

from .serializers import DecDetListSerializer, DecDetDetailSerializer, DecDetCreateSerializer
from .pagination import DecDetListPagination
from ..models import DecDetModel

from CSV.CSV import decdetQuerysetToCSV

import datetime

class DecDetListAPIView(generics.ListAPIView):
    """docstring for DecDetListAPIView."""
    serializer_class    = DecDetListSerializer
    permission_classes  = [permissions.IsAuthenticated]
    pagination_class    = DecDetListPagination

    def get_queryset(self, *args, **kwargs):
        queryset                = DecDetModel.objects.all().order_by("-timestamp")

        query_code              = self.request.GET.get("code",None)
        query_num_decdet        = self.request.GET.get("num_decdet",None)
        query_appurement        = self.request.GET.get("appurement", None)
        query_importateur       = self.request.GET.get("importateur",None)
        query_declarant         = self.request.GET.get("declarant", None)
        query_taux_suspension   = self.request.GET.get("taux_suspension",None)
        query_numero_caution    = self.request.GET.get("numero_caution", None)
        query_numero_contrat    = self.request.GET.get("numero_contrat", None)
        query_objet_contrat     = self.request.GET.get("objet_contrat", None)
        query_lieu_execution    = self.request.GET.get("lieu_execution", None)
        query_num_autors_at     = self.request.GET.get("num_autors_at", None)
        query_year              = self.request.GET.get("year", None)
        query_month             = self.request.GET.get("month", None)

        if query_num_decdet is not None:
            queryset = queryset.filter(Q(num_decdet__icontains = query_num_decdet))
        if query_importateur is not None:
            queryset = queryset.filter(Q(importateur__icontains = query_importateur))
        if query_code is not None:
            queryset = queryset.filter(Q(code = query_code))
        if query_taux_suspension is not None:
            queryset = queryset.filter(Q(taux_suspension = query_taux_suspension))
        if query_declarant is not None:
            queryset = queryset.filter(Q(declarant__icontains = query_declarant))
        if query_objet_contrat is not None:
            queryset = queryset.filter(Q(objet_contrat__icontains = query_objet_contrat))
        if query_lieu_execution is not None:
            queryset = queryset.filter(Q(lieu_execution__icontains = query_lieu_execution))
        if query_numero_caution is not None:
            queryset = queryset.filter(Q(numero_caution__icontains = query_numero_caution))
        if query_num_autors_at is not None:
            queryset = queryset.filter(Q(num_autors_at__icontains = query_num_autors_at))
        if query_year is not None:
            queryset = queryset.filter(Q(date_autors_at__year = query_year))
        if query_month is not None:
            queryset = queryset.filter(Q(date_autors_at__month = query_month))
        last_queryset = queryset
        if query_appurement is not None:
            last_queryset = []
            for decdet in queryset:
                if decdet.getDecdetStatus() == query_appurement:
                    last_queryset.append(decdet)
        decdetQuerysetToCSV(last_queryset)
        return last_queryset

    
class DecDetDetailAPIView(APIView):
    permission_classes  = [permissions.IsAuthenticated]

    def get(self, *args, **kwargs):
        reference= self.request.GET.get("reference", None)
        decdet = get_object_or_404(DecDetModel, reference = reference)
        decdetJSON = DecDetDetailSerializer(decdet).data
        return Response(decdetJSON)

class DecDetCreateAPIView(APIView):
    serializer_class    = DecDetCreateSerializer
    permission_classes  = [permissions.IsAuthenticated]
    # renderer_classes = [renderers.JSONRenderer]

    # def perform_create(self, serializer):
    #     decdet_id = self.kwargs.get('pk')
    #     decdet = get_object_or_404(DecDetModel, pk = decdet_id)
    #     serializer.save(decdet = decdet)

    #rename to get when using the APIView
    def get(self, request, format = None):
        decdet_args = {}

        decdet_args['importateur'] = self.request.GET.get('importateur', None)
        decdet_args['code']  = self.request.GET.get('code', None)
        decdet_args['num_decdet']  = self.request.GET.get('num_decdet', None)
        decdet_args['importateur']  = self.request.GET.get('importateur', None)
        decdet_args['declarant']  = self.request.GET.get('declarant', None)
        decdet_args['val_marchandise']  = self.request.GET.get('val_marchandise', None)
        decdet_args['taux_suspension']  = self.request.GET.get('taux_suspension', None)
        decdet_args['montant_dit']  = self.request.GET.get('montant_dit', None)
        decdet_args['numero_caution']  = self.request.GET.get('numero_caution', None)
        decdet_args['date_caution']  = self.request.GET.get('date_caution', None)
        decdet_args['num_contrat']  = self.request.GET.get('num_contrat', None)
        decdet_args['objet_contrat']  = self.request.GET.get('objet_contrat', None)
        decdet_args['lieu_execution']  = self.request.GET.get('lieu_execution', None)
        decdet_args['duree_contrat']  = self.request.GET.get('duree_contrat', None)
        decdet_args['num_autors_at']  = self.request.GET.get('num_autors_at', None)
        decdet_args['date_autors_at']  = self.request.GET.get('date_autors_at', None)
        decdet_args['duree_decdet']  = self.request.GET.get('duree_decdet', None)

        decdet = DecDetModel.objects.create_decdet(decdet_args)
        if decdet :
            data = DecDetListSerializer(decdet).data
            return Response(data)
        return Response({"message" : "Impossible de créer une déclaration en détail avec ces données en entrée"}, status = 400 )


#http://localhost:8000/decdet/api/create/?code=5&date_caution=2015-08-05&declarant=fads&duree_contrat=5&duree_decdet=10&importateur=aa&lieu_execution=mll&montant_dit=5000000&numero_caution=50&objet_contrat=54djs&taux_suspension=5

#http://localhost:8000/decdet/api/create/? code=dd&importateur=dddd&declarant=d&objet_contrat=dd&lieu_execution=d&duree_contrat=0&taux_suspension=0&duree_decdet=0&montant_dit=0&numero_caution=0&date_caution=06/01/2019

DecDet/templates/decdet_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Création d'une Déclaration en détail{% endblock title %}
{% block container %}


    {% load crispy_forms_tags %}

    <div hidden id="settings"
              decdet_api_create_url="{{decdet_api_create_url}}"
              decdet_list_url = "{{decdet_list_url}}"></div>

        <h2>Création d'une nouvelle Déclaration en détail</h2>
        <br>

      <div class="row">
        <div class="col-7">
          {% include 'decdet_form.html' with submit_value='Créer' %}
          <br>
          <div style="display:none" id="alert-danger" class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Erreur!</strong> <label>Peut-être qu'une déclaration existe déja sous cette réference</label>
          </div>
        </div>
        <div class="col-5" style="margin : 0;">
          Après la création d'une déclaration :
          <br>
          <br>
          <form >
            <input type="radio" name='radio' class="next-action-radio" value="1" checked> Revenir à la liste des déclarations<br>
            <input type="radio" name='radio' class="next-action-radio" value="2"> Aller à la déclaration ajoutée <br>
            <input type="radio" name='radio' class="next-action-radio" value="3"> Ajouter une autre déclaration<br>
          </form>
        </div>
      </div>


        <br>
        <br>
        <br>
        <br>


{% endblock container %}


{% block script %}
<script src="{% static 'scripts/decdet/decdet_create.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(event){
    initCreateDecdet();
  });
</script>
{% endblock script %}

DecDet/templates/decdet_delete.html
{% extends 'base.html' %}

{% block title %}Suppression de la {{object}}{% endblock title %}
{% block container %}


    <input hidden id='settings'
      declaration = {{object}}>

      <h2>Suppression de la {{object}}</h2>
      <br>

    <div class="row">
      <div class="col-7 offset-2">
        <form method="post">
          {% csrf_token %}
          Voulez vous vraiment supprimer la {{object}}? <br>
          <span style="color:red">
            <b>N.B:</b> Tous les articles, appurements, prorogations et transferts associés
            seront supprimés aussi!
          </span>
          <br>
          <br>
          <button id="decdet-delete-btn" style="float:right" type="submit" name="button" class="btn btn-outline-danger">Supprimer</button>
        </form>
      </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>



{% endblock container %}

{% block script %}
  <script type="text/javascript">
    $(document).ready(function () {
      $('#decdet-delete-btn').on('click', function () {
          var declaration = $('#settings').attr('declaration');
          alert('La '+declaration+' a été supprimée avec succès\n'+
              'Ainsi que les articles, appurements, prorogations et transferts associés,');
      });
    });
  </script>
{% endblock script %}

DecDet/templates/decdet_form.html
<form id="create-decdet-form" method="post">
  {% csrf_token %}

  <div class='hr'>
      <span class='hr-title'>Déclaration</span>
  </div>

  <label for="id_code" class="col-form-label  requiredField"> Code <span class="asteriskField">*</span></label>
  <input type="text" name="code" value="{{object.code}}" maxlength="4" class="textinput textInput form-control" required id="id_code" />

  <label for="id_num_decdet" class="col-form-label  requiredField"> N° de la déclaration <span class="asteriskField">*</span>
  </label>
  <input type="text" name="num_decdet" value="{{object.num_decdet}}" maxlength="255" class="textinput textInput form-control" required id="id_num_decdet" />


  <label for="id_importateur" class="col-form-label  requiredField"> Importateur <span class="asteriskField">*</span>
  </label>
  <input type="text" name="importateur" value="{{object.importateur}}" maxlength="255" class="textinput textInput form-control" required id="id_importateur" />


  <label for="id_declarant" class="col-form-label  requiredField"> Déclarant <span class="asteriskField">*</span>
  </label>
  <input type="text" name="declarant" value="{{object.declarant}}" maxlength="255" class="textinput textInput form-control" required id="id_declarant" />


  <label for="id_val_marchandise" class="col-form-label  requiredField"> Valeur marchandise <span class="asteriskField">*</span>
  </label>
  <div class="input-group">
    <input type="number" min="0" name="val_marchandise" value="{{object.val_marchandise}}"  class="numberinput form-control" required id="id_val_marchandise" />
    <div class="input-group-prepend">
      <div class="input-group-text">DA</div>
    </div>
  </div>


  <label for="id_taux_suspension" class="col-form-label  requiredField"> Taux de suspension <span class="asteriskField">*</span>
  </label>
  <div class="input-group">
    <input type="number" min="0" name="taux_suspension" value="{{object.taux_suspension}}"  class="numberinput form-control" required id="id_taux_suspension" />
    <div class="input-group-prepend">
      <div class="input-group-text">%</div>
    </div>
  </div>

  <label for="id_montant_dit" class="col-form-label  requiredField"> Montant D/T <span class="asteriskField">*</span>
  </label>
  <div class="input-group">
    <input type="number" min="0" name="montant_dit" value="{{object.montant_dit}}"  class="numberinput form-control" required id="id_montant_dit" />
    <div class="input-group-prepend">
      <div class="input-group-text">DA</div>
    </div>
  </div>




  <div class='hr'>
      <span class='hr-title'>Caution</span>
  </div>

  <label for="id_numero_caution" class="col-form-label  requiredField"> Numéro caution <span class="asteriskField">*</span>
  </label>
  <input type="text" min="0" name="numero_caution" value="{{object.numero_caution}}"  class="textinput form-control" required id="id_numero_caution" />

  <label for="id_date_caution" class="col-form-label  requiredField"> Date de caution <span class="asteriskField">*</span>
  </label>
  <input type="date" name="date_caution" value="{{object.date_caution|date:'Y-m-d'}}"  class="dateinput form-control" required id="id_date_caution" />
  <!--<input type="hidden" name="initial-date_caution"   id="initial-id_date_caution" />-->

  <div class='hr'>
      <span class='hr-title'>Contrat</span>
  </div>

  <label for="id_num_contrat" class="col-form-label  requiredField"> N° du contrat <span class="asteriskField">*</span>
  </label>
  <input type="text" name="num_contrat" value="{{object.num_contrat}}" maxlength="255" class="textinput textInput form-control" required id="id_num_contrat" />


  <label for="id_objet_contrat" class="col-form-label  requiredField"> Objet du contrat <span class="asteriskField">*</span>
  </label>
  <input type="text" name="objet_contrat" value="{{object.objet_contrat}}" maxlength="255" class="textinput textInput form-control" required id="id_objet_contrat" />

  <label for="id_lieu_execution" class="col-form-label  requiredField"> Lieu d'exécution <span class="asteriskField">*</span>
  </label>
  <input type="text" name="lieu_execution" value="{{object.lieu_execution}}" maxlength="255" class="textinput textInput form-control" required id="id_lieu_execution" />

  <label for="id_duree_contrat" class="col-form-label  requiredField"> Durée du contrat <span class="asteriskField">*</span>
  </label>
  <div class="input-group">
    <input type="number" min="0" name="duree_contrat" value="{{object.duree_contrat}}"  class="numberinput form-control" required id="id_duree_contrat" />
    <div class="input-group-prepend">
      <div class="input-group-text">mois</div>
    </div>
  </div>

  <div class='hr'>
      <span class='hr-title'>Autorisation d'admission</span>
  </div>

  <label for="id_num_autors_at" class="col-form-label  requiredField"> N° de l'autorisation d'admission <span class="asteriskField">*</span>
  </label>
  <input type="text" name="num_autors_at" value="{{object.num_autors_at}}" maxlength="255" class="textinput textInput form-control" required id="id_num_autors_at" />



  <label for="id_date_autors_at" class="col-form-label  requiredField"> Date de l'autorisation d'admission <span class="asteriskField">*</span>
  </label>
  <input type="date" name="date_autors_at" value="{{object.date_autors_at|date:'Y-m-d'}}"  class="dateinput form-control" required id="id_date_autors_at" />

  <label for="id_duree_decdet" class="col-form-label  requiredField"> Durée accordée <span class="asteriskField">*</span>
  </label>
  <div class="input-group">
    <input type="number" min="0" name="duree_decdet" value="{{object.duree_decdet}}"  class="numberinput form-control" required id="id_duree_decdet" />
    <div class="input-group-prepend">
      <div class="input-group-text">mois</div>
    </div>
  </div>


    <br>
    <input id="decdet-create-form-btn" type="submit" class="btn btn-primary" value="{{submit_value}}">
</form>

DecDet/templates/decdet_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Liste des Déclarations en détail{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'styles/decdet/filter_list.css' %}" >
<link rel="stylesheet" href="{% static 'styles/article/appurement.css' %}" >
  <style >
    .table-wrapper-scroll-y {
      display: block;
      max-height: 600px;
      overflow-y: auto;
      -ms-overflow-style: -ms-autohiding-scrollbar;
    }

  </style>
{% endblock css %}


{% block container %}

    <br>
    <input hidden id="settings"
              decdet_api_list_url="{{decdet_api_list_url}}"
              PAGE_SIZE = "{{PAGE_SIZE}}"
                >
    <h2>Liste des Déclarations en détail</h2>
    {% include 'decdet_filter.html' %}
    <span id="decdet-list-html-info"></span>
    <div class="table-wrapper-scroll-y">
      <table id="" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Code</th>
            <th scope="col">N°</th>
            <th scope="col">Importateur</th>
            <th scope="col">Durée accordée (mois)</th>
            <th scope="col">Durée contrat (mois)</th>
            <th scope="col">Statut</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody id="decDet-List-Html-Container">
          <!-- Will be filled with Ajax Call in fetchData() -->
        </tbody>
      </table>
      <!-- <button id="table-to-cs" data-export="export">Excel</button> -->
    </div>
    <br>
    <button id="navigation-fetch-data-btn-previous" type="button" class="btn btn-outline-dark"> Précédent </button>
    <button id="navigation-fetch-data-btn-next" type="button" class="btn btn-outline-dark"> Suivant </button>
    <br>
    <br>
    <button id="article-csv-btn" data-toggle="tooltip" data-placement="top"
          title="Télecharger en CSV" style="float:right;" type="button"
          onclick="location.href='{% static 'CSV/Declarations_en_Detail.csv' %}'"
           class="btn btn-outline-info">
          <i class="fas fa-file-csv fa-4x"></i> </button>

    <br>
    <a href="{{decdet_create_url}}"> <i class="fas fa-plus" style="color:green"></i> Créer une déclaration en détail</a>

{% endblock container %}


{% block script %}
  <script src="{% static 'scripts/decdet/decdet_list.js' %}"></script>
  <script src="{% static 'scripts/decdet/decdet_filter.js' %}" charset="utf-8"></script>


  <!-- <script src="{% static 'scripts/miscs/tabletoCSV.js' %}"></script> -->
  <script type="text/javascript">
    $(document).ready(function(event){
      init();
      decdetFilterInit();
      // $("#export").click(function(){
    	//   $("table").tableToCSV();
    	// });
    });
  </script>
{% endblock script %}

DecDet/templates/decdet_update.html
{% extends 'base.html' %}

{% block title %}Modification de la {{object}}{% endblock title %}
{% block container %}

{% load crispy_forms_tags %}

    <input hidden id='settings'
      object_date_caution = {{object.date_caution|date:"m/d/Y"}}
      object_date_decdet = {{object.date_decdet|date:"m/d/Y"}}>

      <h2>Modification de la {{object}}</h2>
      <br>

    <div class="row">
      <div class="col-7 offset-2">
        <form method="post">
          {% csrf_token %}
          {# {% include 'decdet_form.html' with submit_value='Modifier'  object=object %} #}
          {{form|crispy}}
          <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
      </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>



{% endblock container %}

    <script type="text/javascript">
    $(document).ready(function(event){
        var date_str = $('#settings').attr('object_date_caution');
        var date = new Date(date_str).toISOString().substr(0, 10);
        $('#id_date_caution').val(date);
        var date_str = $('#settings').attr('object_date_decdet');
        var date = new Date(date_str).toISOString().substr(0, 10);
        $('#id_date_decdet').val(date);
    });
    </script>