Transfert/api/urls.py
from django.urls import path, include

from .views import TransfertListAPIView, TransfertCreateAPIView

app_name = 'api-transfert'


urlpatterns = [
    path('list/', TransfertListAPIView.as_view(), name = 'list'),
    path('create/', TransfertCreateAPIView.as_view(), name = 'create'),
]

Transfert/urls.py
from django.urls import path, include

from .views import TransfertDetailView, TransfertListView, TransfertUpdateView, TransfertDecdetListView

app_name = 'transfert'

urlpatterns = [
    path('list/', TransfertListView.as_view(), name = 'list'),
    path('list/<int:pk>', TransfertDecdetListView.as_view(), name = 'decdet-list'),
    path('<int:pk>/', TransfertDetailView.as_view(), name = 'detail'),
    path('update/<int:pk>', TransfertUpdateView.as_view(), name = 'update'),

    path('api/', include('Transfert.api.urls', namespace='api-transfert'))
]

ssac/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from .views import DashBoardView, SSACView

urlpatterns = [
    path('', SSACView.as_view(), name = 'Bienvenue'),
    path('accueil/', DashBoardView.as_view(), name = 'home'),
    path('decdet/', include('DecDet.urls', namespace = 'decdet')),
    path('article/', include('Article.urls', namespace = 'article')),
    path('transfert/', include('Transfert.urls', namespace='transfert')),
    path('prorogation/', include('Prorogation.urls', namespace='prorogation')),
    path('appurement/', include('Appurement.urls', namespace='appurement')),


    path('admin/', admin.site.urls, name = 'admin'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('accounts/', include('django.contrib.auth.urls'))

]

Transfert/models.py
from django.db import models
from django.urls import reverse_lazy
import datetime

from DecDet.models import DecDetModel
from Prorogation.models import ProrogationModel
from Article.models import ArticleModel

class TransfertManager(models.Manager):
    def create_transfert(self, transfert_args):
        transfert = None
        articles_pks = transfert_args['articlesPks']
        if articles_pks is not None:
            try:
                decdet = DecDetModel.objects.get(num_decdet = transfert_args['decdet'])
                try:
                    prorogation = ProrogationModel.objects.get(num_decdet = transfert_args['prorogation'])
                except ProrogationModel.DoesNotExist:
                    prorogation = None
                transfert = self.model(
                    decdet = decdet,
                    prorogation = prorogation,
                    num_contrat = transfert_args['num_contrat'],
                    objet_contrat = transfert_args['objet_contrat'],
                    lieu_execution = transfert_args['lieu_execution'],
                    duree_contrat = transfert_args['duree_contrat'],
                    num_autors_tr = transfert_args['num_autors_tr'],
                    date_autors_tr = transfert_args['date_autors_tr'],
                    objet_autors_tr = transfert_args['objet_autors_tr'],
                    duree_transfert = transfert_args['duree_transfert']
                )
                transfert.save()
                for article_pk in articles_pks:
                    # article = ArticleModel.objects.get(pk = article_pk)
                    transfert.articles.add(article_pk)
            except Exception as e:
                print(e)
        return transfert

    def getApiListUrl(self):
        return reverse_lazy('transfert:api-transfert:list')

    def getArticleSet(self, transfert_pk):
        transfert = TransfertModel.objects.get(pk = transfert_pk)
        return transfert.getArticleSet()

    def getCreateAPIUrl(self):
        return reverse_lazy('transfert:api-transfert:create')



class TransfertModel(models.Model):
    """docstring for TransfertModel."""

    class Meta:
        verbose_name_plural = 'Transferts'

    decdet              = models.ForeignKey(DecDetModel, default=1, on_delete=models.CASCADE, related_name='transfer_set')
    prorogation         = models.ForeignKey(ProrogationModel, blank=True, null=True, on_delete=models.CASCADE, related_name='transfer_set')

    articles            = models.ManyToManyField(ArticleModel, related_name = 'transfert_set', blank=True)

    num_contrat         = models.CharField(max_length = 255, default='')
    objet_contrat       = models.CharField(max_length = 255, default='')
    lieu_execution      = models.CharField(max_length = 255, default='')
    duree_contrat       = models.PositiveIntegerField(default=0)

    num_autors_tr       = models.CharField(max_length = 255, default='')
    date_autors_tr      = models.DateField(default=datetime.date.today)
    objet_autors_tr     = models.CharField(max_length = 255, default='')
    duree_transfert     = models.PositiveIntegerField(default=0)

    timestamp           = models.DateTimeField(auto_now_add=True, blank=True)# date of creation


    objects = TransfertManager()

    def __str__(self):
        return "Transfert n°"+str(self.pk)

    def getDetailUrl(self):
        return reverse_lazy('transfert:detail', kwargs = {'pk':self.pk})

    def getUpdateUrl(self):
        return reverse_lazy('transfert:update', kwargs = {'pk':self.pk})

    def getArticleSet(self):
        return self.articles.all()

Transfert/forms.py
from django import forms

from .models import TransfertModel

class TransfertUpdateForm(forms.ModelForm):
    class Meta:
        model = TransfertModel
        fields = '__all__'

Transfert/api/views.py
from rest_framework import generics, permissions
from rest_framework.views import APIView
from rest_framework.response import Response

from .pagination import TransfertListPagination
from .serializers import TransfertSerializer, TransfertListSerializer

from ..models import TransfertModel

class TransfertListAPIView(generics.ListAPIView):
    serializer_class = TransfertSerializer
    pagination_class = TransfertListPagination
    permission_classes  = [permissions.IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = TransfertModel.objects.all().order_by("-timestamp")
        return queryset


class TransfertCreateAPIView(APIView):
    """docstring for ArticleTransfertAPIView."""
    def get(self, request, format = None):
        transfert_args = {}
        transfert_args['decdet'] = self.request.GET.get('decdet', None)
        transfert_args['prorogation'] = self.request.GET.get('prorogation', None)
        transfert_args['articlesPks'] = self.request.GET.get('articlesPks', None)
        transfert_args['num_contrat'] = self.request.GET.get('num_contrat', None)
        transfert_args['objet_contrat'] = self.request.GET.get('objet_contrat', None)
        transfert_args['lieu_execution'] = self.request.GET.get('lieu_execution', None)
        transfert_args['duree_contrat'] = self.request.GET.get('duree_contrat', None)
        transfert_args['num_autors_tr'] = self.request.GET.get('num_autors_tr', None)
        transfert_args['date_autors_tr'] = self.request.GET.get('date_autors_tr', None)
        transfert_args['objet_autors_tr'] = self.request.GET.get('objet_autors_tr', None)
        transfert_args['duree_transfert'] = self.request.GET.get('duree_transfert', None)
        articlePks = transfert_args['articlesPks']

        if articlePks:
            articlePks = articlePks.split(',')
            transfert = TransfertModel.objects.create_transfert(transfert_args)
            if transfert:
                return Response({"message" : "Transfert effectué avec succès"}, status = 200)
            return Response({"message" : "4"}, status = 400 )
        return Response({"message" : "Impossible de transférer d'articles avec ces données en entrée"}, status = 400 )

Transfert/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic

from .forms import TransfertUpdateForm
from .models import TransfertModel

from Prorogation.models import ProrogationModel
from DecDet.models import DecDetModel

from CSV.CSV import articleQuerysetToCSV

class TransfertListView(generic.ListView, LoginRequiredMixin):
    model = TransfertModel
    template_name = "transfert_list.html"

    def get_queryset(self, *args, **kwargs):
        queryset = TransfertModel.objects.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(TransfertListView, self).get_context_data()
        context['transfert_api_list_url'] = TransfertModel.objects.getApiListUrl()
        return context


class TransfertDecdetListView(generic.ListView, LoginRequiredMixin):
    model = TransfertModel
    template_name = "transfert_decdet_list.html"

    def get_queryset(self, *args, **kwargs):
        queryset = None
        pk = self.kwargs.get('pk')
        try:
            at = DecDetModel.objects.get(pk = pk)
            queryset = at.transfer_set.all()
        except DecDetModel.DoesNotExist:
            try:
                prorogation = ProrogationModel.objects.get(pk = pk)
                queryset = prorogation.decdet.transfer_set.all()
            except ProrogationModel.DoesNotExist:
                pass
        return queryset.order_by('-timestamp')

    def get_context_data(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        at = None
        try:
            at = DecDetModel.objects.get(pk = pk)
        except DecDetModel.DoesNotExist:
            try:
                prorogation = ProrogationModel.objects.get(pk = pk)
                at = prorogation.decdet
            except ProrogationModel.DoesNotExist:
                pass
        context = super(TransfertDecdetListView, self).get_context_data()
        context['decdet']     = at
        return context




class TransfertDetailView(generic.DetailView, LoginRequiredMixin):
    model = TransfertModel
    template_name = "transfert_detail.html"

    def get_object(self, *args, **kwargs):
        transfert_pk = self.kwargs.get('pk')
        transfert = get_object_or_404(TransfertModel, pk = transfert_pk)
        articleQuerysetToCSV(transfert.articles.all())
        return transfert

    def get_context_data(self, *args, **kwargs):
        transfert_pk = self.kwargs.get('pk')
        transfert = TransfertModel.objects.get(pk = transfert_pk)
        context = super(TransfertDetailView, self).get_context_data()
        context['date_creation']        = transfert.timestamp.strftime('%A %d %B %Y')
        context['temps_creation']       = transfert.timestamp.strftime('%H:%M:%S')

        return context


class TransfertUpdateView(generic.UpdateView, LoginRequiredMixin):
    form_class = TransfertUpdateForm
    template_name = "transfert_update.html"

    def get_object(self, *args, **kwargs):
        transfert_pk = self.kwargs.get('pk')
        transfert = get_object_or_404(TransfertModel, pk = transfert_pk)
        return transfert

Transfert/templates/transfert_decdet_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Liste des transferts concernant la {{decdet}}{% endblock title %}

{% block css %}

{% endblock css %}

{% block container %}

    <h2>Liste des transferts de l' {{decdet}}</h2>
    <br> <br>
    Déclaration en détail racine (AT) N°: <b>{{decdet.num_decdet}}</b>  <a href="{{decdet.getDetailUrl}}"><i class="fas fa-angle-double-right"></i></a>
    <br>
    <br>
    <br>
    <table id="" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead class="thead-dark">
        <tr>
          <th scope="col">N° Déclaration mère</th>
          <th scope="col">N° Contrat</th>
          <th scope="col">Durée du contrat</th>
          <th scope="col">Durée accordée</th>
          <th scope="col">Nombre d'articles</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="transfert-List-Html-Container">
        {% for transfert in  object_list %}
          <tr>
            {% if transfert.prorogation %}
              <td>{{transfert.prorogation.num_decdet}}</td>
            {% else %}
              <td> <b>AT</b> </td>
            {% endif %}
            <td>{{transfert.num_contrat}}</td>
            <td>{{transfert.duree_contrat}}</td>
            <td>{{transfert.duree_transfert}}</td>
            <td>{{transfert.articles.all|length}}</td>
            <td>
              <a href="{{transfert.getDetailUrl}}" data-toggle="tooltip"
                data-placement="top" title="Détail du transfert">
                <i class="fas fa-angle-double-right"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <br>
  <!-- <button id="navigation-fetch-data-btn-previous" type="button" class="btn btn-outline-dark"> Précédent </button> -->
  <!-- <button id="navigation-fetch-data-btn-next" type="button" class="btn btn-outline-dark"> Suivant </button> -->

{% endblock container %}

{% block script %}
  <script src="{% static 'scripts/transfert/transfert_list.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function(event){
      init();
    });
  </script>
{% endblock script %}

Transfert/templates/transfert_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{object}}{% endblock title %}


{% block container %}
    <h2>Détail du Transfert</h2> <br><br>
    <div class="row">
      <div class="col-8 offset-2">
        N° de l'Admission temporaire : <b>{{object.decdet.num_decdet}}</b> : <a href="{{object.decdet.getDetailUrl}}"data-toggle="tooltip"
          data-placement="top" title="Détail de la déclaration"><i class="fas fa-angle-double-right fa-1x"></i></a><br>
          {% if object.prorogation %}
            Transfert effectué à partir de la prorogation N° : <b>{{object.prorogation.num_decdet}}</b> :  <a href="{{object.prorogation.getDetailUrl}}"data-toggle="tooltip"
            data-placement="top" title="Détail de la déclaration"><i class="fas fa-angle-double-right fa-1x"></i></a><br>
          {% endif %}
          <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-5 offset-1">
        N° Contrat   : <b>{{object.num_contrat}}</b> <br>
        Objet du contrat   : {{object.objet_contrat}} <br>
        Lieu d'execution   : {{object.lieu_execution}} <br>
        Duree du contrat   : <b>{{object.duree_contrat}} mois </b><br>
      </div>
      <div class="col-5">
        N° de l' autorisation du transfert   : {{object.num_autors_tr}} <br>
        Date de l' autorisation du transfert : {{object.date_autors_tr}} <br>
        Objet de l' autorisation du transfert : {{object.objet_autors_tr}} <br>
        Duree accordée  : <b>{{object.duree_transfert}} mois </b><br>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-5 offset-6">
        Date de création système : {{date_creation}} à {{temps_creation}} <br>
      </div>
    </div>

      <h3> Articles associés ({{object.getArticleSet|length}})</h3>
        <br>
    <table id="" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead class="thead-dark">
        <tr>
          <th scope="col">N° Série</th>
          <th scope="col">Position Tarifaire</th>
          <th scope="col">Valeur (DA)</th>
          <th scope="col">Qte</th>
          <th scope="col">Description</th>
        </tr>
      </thead>
      <tbody id="transfert-List-Html-Container">
        {% for article in object.getArticleSet %}
        <tr>
          <td>{{article.num_serie}}</td>
          <td>{{article.position_tarifaire}}</td>
          <td>{{article.valeur}}</td>
          <td>{{article.quantite}}</td>
          <td>{{article.description}}</td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
    <button id="article-csv-btn" data-toggle="tooltip" data-placement="top"
          title="Télecharger en CSV" style="float:right;" type="button"
          onclick="location.href='{% static 'CSV/Articles.csv' %}'"
           class="btn btn-outline-info">
          <i class="fas fa-file-csv fa-4x"></i> </button>


    {{article_set}}

{% endblock container %}

Transfert/templates/transfert_form.html
<form id="transfert-create-form" method="post">
  {% csrf_token %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        {% if transfert_depuis_prorogaiton %}
        <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
        <input readonly type="text" name="decdet" value="{{object.decdet.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />

        <label for="id_decdet" class="col-form-label  requiredField"> N° Prorogation mère <span class="asteriskField">*</span></label>
        <input readonly type="text" name="prorogation" value="{{object.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />

        {% else %}
          <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
          <input readonly type="text" name="decdet" value="{{object.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-6 offset-0">
        <div class='hr'>
            <span class='hr-title'>Contrat</span>
        </div>

        <label for="id_num_contrat" class="col-form-label  requiredField"> N° du contrat <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_contrat" value="" maxlength="255" class="textinput textInput form-control" required id="id_num_contrat" />

        <label for="id_objet_contrat" class="col-form-label  requiredField"> Objet du contrat <span class="asteriskField">*</span>
        </label>
        <input type="text" name="objet_contrat" value="" maxlength="255" class="textinput textInput form-control" required id="id_objet_contrat" />

        <label for="id_lieu_execution" class="col-form-label  requiredField"> Lieu d'exécution <span class="asteriskField">*</span>
        </label>
        <input type="text" name="lieu_execution" value="" maxlength="255" class="textinput textInput form-control" required id="id_lieu_execution" />

        <label for="id_duree_contrat" class="col-form-label  requiredField"> Durée du contrat <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="duree_contrat" value=""  class="numberinput form-control" required id="id_duree_contrat" />
          <div class="input-group-prepend">
            <div class="input-group-text">mois</div>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class='hr'>
            <span class='hr-title'>Autorisation de transfert</span>
        </div>

        <label for="id_num_autors_tr" class="col-form-label  requiredField"> N° de l'autorisation de transfert <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_autors_tr" value="" maxlength="255" class="textinput textInput form-control" required id="id_num_autors_tr" />

        <label for="id_date_autors_tr" class="col-form-label  requiredField"> Date de l'autorisation de transfert <span class="asteriskField">*</span>
        </label>
        <input type="date" name="date_autors_tr" value=""  class="dateinput form-control" required id="id_date_autors_tr" />

        <label for="id_objet_autors_tr" class="col-form-label  requiredField"> Objet de l'autorisation de transfert <span class="asteriskField">*</span>
        </label>
        <input type="text" name="objet_autors_tr" value=""  class="dateinput form-control" required id="id_objet_autors_tr" />

        <label for="id_duree_transfert" class="col-form-label  requiredField"> Durée accordée <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="duree_transfert" value=""  class="numberinput form-control" required id="id_duree_transfert" />
          <div class="input-group-prepend">
            <div class="input-group-text">mois</div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <br>
    <input hidden type="submit">
</form>

Transfert/templates/transfert_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Liste des transferts{% endblock title %}

{% block css %}

  <style >
    .table-wrapper-scroll-y {
      display: block;
      max-height: 600px;
      overflow-y: auto;
      -ms-overflow-style: -ms-autohiding-scrollbar;
    }

  </style>
{% endblock css %}

{% block container %}
  <div hidden id="settings" transfert_api_list_url={{transfert_api_list_url}}></div>

  <h2>Liste des transferts</h2>
  <br>

  <span id="transfert-list-html-info"></span>
  <div class="table-wrapper-scroll-y">
    <table id="" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Ancienne Déclaration</th>
          <th scope="col">Nouvelle Déclaration</th>
          <th scope="col">Date de transfert</th>
          <th scope="col">Nombre d'articles</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="transfert-List-Html-Container">
        <!-- Will be filled with Ajax Call in fetchData() -->
      </tbody>
    </table>
  </div>
  <br>
  <button id="navigation-fetch-data-btn-previous" type="button" class="btn btn-outline-dark"> Précédent </button>
  <button id="navigation-fetch-data-btn-next" type="button" class="btn btn-outline-dark"> Suivant </button>

{% endblock container %}

{% block script %}
  <script src="{% static 'scripts/transfert/transfert_list.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function(event){
      init();
    });
  </script>
{% endblock script %}

Transfert/templates/transfert_update.html
{% extends 'base.html' %}

{% block title %}Modifier un transfert{% endblock title %}


{% block container %}
    {% load crispy_forms_tags %}
    <form >
      {% csrf_token %}
      {{form|crispy}}
      <input class="btn btn-primary" type="submit" value="Modifier">
    </form>
{% endblock container %}

Transfert/templates/transfert_update_form.html
{% load crispy_forms %}
<form >
  {% csrf_token %}
  {{form|crispy}}
  <input class="btn btn-primary" type="submit" value="Modifier">
</form>