Appurement/urls.py
from django.urls import path

from .views import AppurementListView, AppurementDetailView

app_name = 'Appurement'

urlpatterns = [
    path('list/<int:decdet_pk>', AppurementListView.as_view(), name = 'decdet-list'),
    path('<int:pk>', AppurementDetailView.as_view(), name = 'detail')
]

ssac/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from .views import DashBoardView, SSACView

urlpatterns = [
    path('', SSACView.as_view(), name = 'Bienvenue'),
    path('accueil/', DashBoardView.as_view(), name = 'home'),
    path('decdet/', include('DecDet.urls', namespace = 'decdet')),
    path('article/', include('Article.urls', namespace = 'article')),
    path('transfert/', include('Transfert.urls', namespace='transfert')),
    path('prorogation/', include('Prorogation.urls', namespace='prorogation')),
    path('appurement/', include('Appurement.urls', namespace='appurement')),


    path('admin/', admin.site.urls, name = 'admin'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('accounts/', include('django.contrib.auth.urls'))

]

Appurement/models.py
from django.db import models
from django.urls import reverse_lazy
import datetime

from DecDet.models import DecDetModel
from Article.models import ArticleModel

class AppurementManager(models.Manager):
    def create_apurement(self, appurement_args):
        appurement = None
        create_appurement = True
        articles_pks = appurement_args['articlesPks']
        for article_pk in articles_pks:
            article = ArticleModel.objects.get(pk = article_pk)
            if article.appure:
                create_appurement = False
        if create_appurement:
            #Apurement par déclaration
            try:
                print(appurement_args['decdet'])
                decdet = DecDetModel.objects.get(num_decdet = appurement_args['decdet'])
                if appurement_args['num_decdet']:
                    appurement = self.model(
                        decdet = decdet,
                        date_appurement = appurement_args['date_appurement'],
                        objet_appurement = appurement_args['objet_appurement'],
                        code = appurement_args['code'],
                        num_decdet = appurement_args['num_decdet'],
                        importateur = appurement_args['importateur'],
                        declarant = appurement_args['declarant'],
                        val_marchandise = appurement_args['val_marchandise'],
                        taux_suspension = appurement_args['taux_suspension'],
                        montant_dit = appurement_args['montant_dit'],
                        num_appurement = appurement_args['num_appurement']
                    )
                    appurement.save()
                #Apurement par décision
                else:
                    appurement = self.model(
                        decdet = decdet,
                        date_appurement = appurement_args['date_appurement'],
                        objet_appurement = appurement_args['objet_appurement'],
                        num_decision = appurement_args['num_decision'],
                        num_appurement = appurement_args['num_appurement']
                    )
                    appurement.save()
                for article_pk in articles_pks:
                        article = ArticleModel.objects.get(pk = article_pk)
                        article.apurer()
                        appurement.articles.add(article)
            except (DecDetModel.DoesNotExist, ArticleModel.DoesNotExist) as e:
                print(e)
            return appurement

    def getApiListUrl(self):
        return reverse_lazy('appurement:api-appurement:list')

    def getArticleSet(self, appurement_pk):
        appurement = AppurementModel.objects.get(pk = appurement_pk)
        return appurement.getArticleSet()



class AppurementModel(models.Model):
    """docstring for AppurementModel."""

    class Meta:
        verbose_name_plural = 'Appurements'

    decdet          = models.ForeignKey(DecDetModel, default=1, on_delete=models.CASCADE, related_name='appurement_set')
    articles        = models.ManyToManyField(ArticleModel, related_name = 'appurement_set')
    date_appurement = models.DateField(default=datetime.date.today)
    objet_appurement= models.TextField(max_length=255)
    num_appurement  = models.CharField(max_length = 255, default='', blank = True)

    num_decision    = models.CharField(max_length = 255, null = True, blank = True)

    code            = models.CharField(max_length = 4, default='', null = True, blank = True)
    num_decdet      = models.CharField(max_length = 255, default='',  null = True, blank = True)
    importateur     = models.CharField(max_length = 255, default='', null = True, blank = True)
    declarant       = models.CharField(max_length = 255, default='', null = True, blank = True)
    val_marchandise = models.PositiveIntegerField(default=0, null = True, blank = True)
    taux_suspension = models.PositiveIntegerField(default=0, null = True, blank = True)
    montant_dit     = models.PositiveIntegerField(default=0, null = True, blank = True)



    timestamp       = models.DateTimeField(auto_now_add=True, blank=True)# date of creation


    objects = AppurementManager()

    def __str__(self):
        return "Apurement n°"+str(self.num_appurement)

    def getDetailUrl(self):
        return reverse_lazy('appurement:detail', kwargs = {'pk':self.pk})

    def getArticleSet(self):
        return self.articles.all()

    def getDetailUrl(self):
        return reverse_lazy('appurement:detail', kwargs={'pk':self.pk})

Appurement/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic

from .models import AppurementModel
from DecDet.models import DecDetModel

from CSV.CSV import articleQuerysetToCSV


class AppurementListView(generic.ListView, LoginRequiredMixin):
    model = AppurementModel
    template_name = "appurement_decdet_list.html"

    def get_queryset(self, *args, **kwargs):
        decdet_pk = self.kwargs.get('decdet_pk')
        queryset  = AppurementModel.objects.filter(decdet = decdet_pk)
        return queryset

    def get_context_data(self, *args, **kwargs):
        decdet_pk = self.kwargs.get('decdet_pk')
        decdet = get_object_or_404(DecDetModel, pk = decdet_pk)
        context = super(AppurementListView, self).get_context_data()
        context['decdet'] = decdet
        return context


class AppurementDetailView(generic.DetailView, LoginRequiredMixin):
    model = AppurementModel
    template_name = "appurement_detail.html"

    def get_object(self, *args, **kwargs):
        object = super(AppurementDetailView, self).get_object()
        articleQuerysetToCSV(object.articles.all())
        return object

    # def get_context_data(self, *args, **kwargs):
    #     decdet_pk = self.kwargs.get('decdet_pk')
    #     decdet = AppurementModel.objects.get(pk = decdet_pk)
    #     context = super(AppurementListView, self).get_context_data()
    #     context['decdet'] = decdet
    #     return context

Appurement/templates/appurement_decdet_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Liste des apurements de la {{decdet}}{% endblock title %}

{% block css %}

  <style >

  </style>
{% endblock css %}

{% block container %}
  <div hidden id="settings"></div>
  <h2>Liste des apurements de la {{decdet}}</h2>
  <br>

  Déclaration en détail racine (AT) N°: <b>{{decdet.num_decdet}}</b>  <a href="{{decdet.getDetailUrl}}"><i class="fas fa-angle-double-right"></i></a>
  <br><br>

  <span id="appurement-list-html-info"></span>
    <table id="" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead class="thead-dark">
        <tr>
          <th scope="col">N° Admission temporaire</th>
          <th scope="col">N° Apurement</th>
          <th scope="col">Type de l'apurement</th>
          <th scope="col">Date de l'apurement</th>
          <th scope="col">Objet de l'apurement</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody id="appurement-List-Html-Container">
        {% for appurement in object_list %}
          <tr>
            <td>{{appurement.decdet.num_decdet}}</td>
            <td>{{appurement.num_appurement}}</td>
            {% if appurement.num_decision %}
              <td> <b>Décision</b> </td>
            {% else %}
              <td> <b>Déclaration</b> </td>
            {% endif %}
            <td>{{appurement.date_appurement}}</td>
            <td>{{appurement.objet_appurement}}</td>
            <td>
              <a href="{{appurement.getDetailUrl}}" data-toggle="tooltip"
                data-placement="top" title="Détail de l'appurement">
                <i class="fas fa-angle-double-right"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <br>

{% endblock container %}

Appurement/templates/appurement_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Détail de l'{{object}}{% endblock title %}

{% block css %}

  <style >

  </style>
{% endblock css %}

{% block container %}
  <div hidden id="settings"></div>
  <h2>{{object}}</h2>

  <div class="row">
    <div class="col-5 offset-1">
      N° de la déclaration en détail Racine (AT) :     {{object.decdet.num_decdet}} <br>
      Date de l'appurement           :     {{object.date_appurement}} <br>
      Objet de l'appurement          :     {{object.objet_appurement}} <br>
      Type de l'appurement           :
        {% if object.num_decision %}
          Décision N°<b>{{object.num_decision}}</b>
        {% else %}
          <b>Déclaration</b>
        {% endif %}
      <br>
      Date Système                   :     {{object.timestamp}} <br>
      <br>
    </div>
    {% if object.num_decdet %}
        <div class="col-5">
          Code          : <b>{{object.code}} </b><br>
          N° Déclaration  : <b>{{object.num_decdet}}</b> <br>
          Importateur   : <b>{{object.importateur}}</b> <br>
          Déclarant     : {{object.declarant}} <br>
          Valeur marchandise   : {{object.val_marchandise}} DA<br>
          Taux de suspension : <b>{{object.taux_suspension}}%</b> <br>
          Montant D/T   : {{object.montant_dit}} DA<br>
        </div>
    {% endif %}
  </div>



  <hr>
  <br>
  <h3>Articles Apurés ({{object.articles.all|length}})</h3>
  <br>
  <table id="" class="table table-striped table-bordered table-sm" cellspacing="1" width="100%">
    <thead class="thead-dark">
      <tr>
        <th scope="col">N° de série</th>
        <th scope="col">Position tarifaire</th>
        <th scope="col">Valeur (DA)</th>
        <th scope="col">Qte</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    <tbody id="article-List-Html-Container">
      {% for article in object.articles.all %}
        <tr>
          <td>{{article.num_serie}}</td>
          <td>{{article.position_tarifaire}}</td>
          <td>{{article.valeur}}</td>
          <td>{{article.quantite}}</td>
          <td>{{article.description}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <button id="article-csv-btn" data-toggle="tooltip" data-placement="top"
        title="Télecharger en CSV" style="float:right;" type="button"
        onclick="location.href='{% static 'CSV/Articles.csv' %}'"
         class="btn btn-outline-info">
        <i class="fas fa-file-csv fa-4x"></i> </button>
  <br>

{% endblock container %}

Appurement/templates/appurement_form_decdet.html
<form id="create-appurement-form-decdet" method="post" class="apurement-form">
  {% csrf_token %}

    {% if apurement_depuis_prorogaiton %}
    <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
    <input readonly type="text" name="decdet" value="{{object.decdet.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />
    {% else %}
      <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
      <input readonly type="text" name="decdet" value="{{object.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />
    {% endif %}


  <div class="row">
    <div class="col-6 offset-3">

      <label for="id_date_appurement" class="col-form-label  requiredField"> Date de l'apurement <span class="asteriskField">*</span>
      </label>
      <input type="date" name="date_appurement" value="{{object.date_appurement|date:'Y-m-d'}}"  class="dateinput form-control" required id="id_date_appurement" />

      <label for="id_objet_appurement" class="col-form-label  requiredField"> Objet de l'apurement <span class="asteriskField">*</span>
      </label>
      <textarea cols="50" rows="2" type="text" name="objet_appurement" value="{{object.objet_appurement}}"  class="dateinput form-control" required id="id_objet_appurement"></textarea>

      <label for="id_num_appurement" class="col-form-label  requiredField"> N° de l'apurement <span class="asteriskField">*</span>
      </label>
      <input type="text" name="num_appurement" value="{{object.num_appurement}}" maxlength="255" class="textinput textInput form-control" required id="id_num_appurement" />

    </div>
  </div>



  <div class='hr'>
      <span class='hr-title'>Déclaration</span>
  </div>

  <div class="row">
    <div class="col-5 offset-1">

        <label for="id_code" class="col-form-label  requiredField"> Code <span class="asteriskField">*</span></label>
        <input type="text" name="code" value="{{object.code}}" maxlength="4" class="textinput textInput form-control" required id="id_code" />

        <label for="id_num_decdet" class="col-form-label  requiredField"> N° de la déclaration <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_decdet" value="{{object.num_decdet}}" maxlength="255" class="textinput textInput form-control" required id="id_num_decdet" />


        <label for="id_importateur" class="col-form-label  requiredField"> Importateur <span class="asteriskField">*</span>
        </label>
        <input type="text" name="importateur" value="{{object.importateur}}" maxlength="255" class="textinput textInput form-control" required id="id_importateur" />


        <label for="id_declarant" class="col-form-label  requiredField"> Déclarant <span class="asteriskField">*</span>
        </label>
        <input type="text" name="declarant" value="{{object.declarant}}" maxlength="255" class="textinput textInput form-control" required id="id_declarant" />
    </div>

    <div class="col-5">

        <label for="id_val_marchandise" class="col-form-label  requiredField"> Valeur marchandise <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="val_marchandise" value="{{object.val_marchandise}}"  class="numberinput form-control" required id="id_val_marchandise" />
          <div class="input-group-prepend">
            <div class="input-group-text">DA</div>
          </div>
        </div>


        <label for="id_taux_suspension" class="col-form-label  requiredField"> Taux de suspension <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="taux_suspension" value="{{object.taux_suspension}}"  class="numberinput form-control" required id="id_taux_suspension" />
          <div class="input-group-prepend">
            <div class="input-group-text">%</div>
          </div>
        </div>

        <label for="id_montant_dit" class="col-form-label  requiredField"> Montant D/T <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="montant_dit" value="{{object.montant_dit}}"  class="numberinput form-control" required id="id_montant_dit" />
          <div class="input-group-prepend">
            <div class="input-group-text">DA</div>
          </div>
        </div>
    </div>
  </div>



  <br>
  <input type="submit" hidden>
</form>

Appurement/templates/appurement_form_decision.html
<form id="create-appurement-form-decision" method="post" class="apurement-form">
  {% csrf_token %}

  {% if apurement_depuis_prorogaiton %}
    <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
    <input readonly type="text" name="decdet" value="{{object.decdet.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />
  {% else %}
    <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
    <input readonly type="text" name="decdet" value="{{object.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />
  {% endif %}

  <div class='hr'>
      <span class='hr-title'>Décision</span>
  </div>

  <div class="row">
    <div class="col-6 offset-3">

        <label for="id_num_decision" class="col-form-label  requiredField"> N° de la décision d'apurement <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_decision" value="{{object.num_decision}}" maxlength="255" class="textinput textInput form-control" required id="id_num_decision" />

        <label for="id_date_appurement" class="col-form-label  requiredField"> Date de l'apurement <span class="asteriskField">*</span>
        </label>
        <input type="date" name="date_appurement" value="{{object.date_appurement|date:'Y-m-d'}}"  class="dateinput form-control" required id="id_date_appurement" />

        <label for="id_objet_appurement" class="col-form-label  requiredField"> Objet de l'apurement <span class="asteriskField">*</span>
        </label>
        <textarea cols="50" rows="2" type="text" name="objet_appurement" value="{{object.objet_appurement}}"  class="dateinput form-control" required id="id_objet_appurement"></textarea>

        <label for="id_num_appurement" class="col-form-label  requiredField"> N° de l'apurement <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_appurement" value="{{object.num_appurement}}" maxlength="255" class="textinput textInput form-control" required id="id_num_appurement" />


    </div>
  </div>
    <br>
    <input type="submit" hidden>
</form>