Prorogation/api/urls.py
from django.urls import path, include

from .views import ProrogationDecdetAPIView, ProrogationListAPIView

app_name = 'api-prorogation'

urlpatterns = [
    path('create/', ProrogationDecdetAPIView.as_view(), name = 'create'),
    path('list/<int:decdet_pk>', ProrogationListAPIView.as_view(), name = 'list'),
]

Prorogation/urls.py
from django.urls import path, include

from .views import ProrogationDecdetListView, ProrogationDetailView, ProrogationUpdateView

app_name='Prorogation'

urlpatterns = [
    path('list/<int:pk>',  ProrogationDecdetListView.as_view(), name='list'),
    path('<int:pk>',  ProrogationDetailView.as_view(), name='detail'),
    path('update/<int:pk>',  ProrogationUpdateView.as_view(), name='update'),
    path('api/', include('Prorogation.api.urls', namespace='api-prorogation')),
]

ssac/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from .views import DashBoardView, SSACView

urlpatterns = [
    path('', SSACView.as_view(), name = 'Bienvenue'),
    path('accueil/', DashBoardView.as_view(), name = 'home'),
    path('decdet/', include('DecDet.urls', namespace = 'decdet')),
    path('article/', include('Article.urls', namespace = 'article')),
    path('transfert/', include('Transfert.urls', namespace='transfert')),
    path('prorogation/', include('Prorogation.urls', namespace='prorogation')),
    path('appurement/', include('Appurement.urls', namespace='appurement')),


    path('admin/', admin.site.urls, name = 'admin'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('accounts/', include('django.contrib.auth.urls'))

]

Prorogation/models.py
from django.db import models
from django.urls import reverse_lazy
import datetime

from DecDet.models import DecDetModel

class ProrogationManager(models.Manager):


    def getDureeMaxProrogation(self, object):
        duree = self. getTotalDurees(object)
        # if isinstance(object, DecDetModel):
        #     decdet = object
        #     date_debut = decdet.date_autors_at
        # elif isinstance(object, ProrogationModel):
        #     prorogation = object
        #     date_debut = prorogation.decdet.date_autors_at
        # else:
        #     return 0
        # dureeRestante = (date_debut + datetime.timedelta(days=30)*duree) - datetime.datetime.now().date()
        # return dureeRestante.days/30
        return object.duree_contrat - duree

    def getTotalDurees(self, object):
        if isinstance(object, DecDetModel):
            decdet = object
            return decdet.duree_decdet
        elif isinstance(object, ProrogationModel):
            prorogation = object
            duree_at = prorogation.decdet.duree_decdet
            durees_pr = 0
            while prorogation is not None:
                durees_pr += prorogation.duree_decdet
                prorogation = prorogation.prorogation_mere
            return duree_at + durees_pr
        else:
            return 0

    def getCreateAPIUrl(self):
        return reverse_lazy('prorogation:api-prorogation:create')

    def create_prorogation(self, prorogation_args, *args, **kwargs):
        try:
            decdet = DecDetModel.objects.get(num_decdet = prorogation_args['decdet'])
            try:
                prorogation_mere = ProrogationModel.objects.get(num_decdet = prorogation_args['prorogation_mere'])
            except ProrogationModel.DoesNotExist:
                prorogation_mere = None
            prorogation = self.model(
                decdet          = decdet,
                prorogation_mere= prorogation_mere,
                code            = prorogation_args['code'],
                num_decdet      = prorogation_args['num_decdet'],
                importateur     = prorogation_args['importateur'],
                declarant       = prorogation_args['declarant'],
                val_marchandise = prorogation_args['val_marchandise'],
                taux_suspension = prorogation_args['taux_suspension'],
                montant_dit     = prorogation_args['montant_dit'],
                numero_caution  = prorogation_args['numero_caution'],
                date_caution    = prorogation_args['date_caution'],
                num_contrat     = prorogation_args['num_contrat'],
                objet_contrat   = prorogation_args['objet_contrat'],
                lieu_execution  = prorogation_args['lieu_execution'],
                duree_contrat   = prorogation_args['duree_contrat'],
                num_autors_pr   = prorogation_args['num_autors_pr'],
                date_autors_pr  = prorogation_args['date_autors_pr'],
                duree_decdet    = prorogation_args['duree_decdet']
            )
            prorogation.save()

        except Exception as e:
            print(e)
            prorogation = None
        return prorogation



    def getApiListUrl(self):
        return reverse_lazy('prorogation:api-prorogation:list')





class ProrogationModel(models.Model):
    """docstring for ProrogationModel."""

    class Meta:
        verbose_name_plural = 'Prorogations'

    decdet              = models.ForeignKey(DecDetModel, default=1, on_delete=models.CASCADE, related_name='prorogation_set')
    prorogation_mere    = models.ForeignKey('self', on_delete=models.CASCADE, related_name='prorogation_filles', blank=True, null=True)

    code            = models.CharField(max_length = 4, default='')
    num_decdet      = models.CharField(max_length = 255, default='', unique = True)
    importateur     = models.CharField(max_length = 255, default='')
    declarant       = models.CharField(max_length = 255, default='')
    val_marchandise = models.PositiveIntegerField(default=0)
    taux_suspension = models.PositiveIntegerField(default=0)
    montant_dit     = models.PositiveIntegerField(default=0)


    numero_caution  = models.CharField(max_length = 255, default='')
    date_caution    = models.DateField(default=datetime.date.today)

    num_contrat     = models.CharField(max_length = 255, default='')
    objet_contrat   = models.CharField(max_length = 255, default='')
    lieu_execution  = models.CharField(max_length = 255, default='')
    duree_contrat   = models.PositiveIntegerField(default=0)

    num_autors_pr   = models.CharField(max_length = 255, default='')
    date_autors_pr  = models.DateField(default=datetime.date.today)
    duree_decdet    = models.PositiveIntegerField(default=0)

    timestamp       = models.DateTimeField(auto_now_add=True, blank=True)# date of creation


    objects = ProrogationManager()

    def __str__(self):
        return "Prorogation n°"+str(self.num_decdet)

    def getDetailUrl(self):
        return reverse_lazy('prorogation:detail', kwargs = {'pk':self.pk})

    def getUpdateUrl(self):
        return reverse_lazy('prorogation:update', kwargs = {'pk':self.pk})

    def getProrogationListUrl(self, *args, **kwargs):
        return reverse_lazy('prorogation:list', kwargs={'pk' : self.pk})

    def getDureeEcoulee(self):
        return ProrogationModel.objects.getTotalDurees(self) - self.duree_decdet

    def getArticleListApiUrl(self):
        return reverse_lazy('article:api-article:prorogation', kwargs = {'prorogation_pk' : self.pk})

    def getUpdateUrl(self):
        return reverse_lazy('prorogation:update', kwargs = {'pk' : self.pk})

    def get_absolute_url(self):
        return self.getDetailUrl()

    def getTransfertsListUrl(self, *args, **kwargs):
        return reverse_lazy('transfert:decdet-list', kwargs={'pk' : self.pk})

    def getAppurementApiCreateUrl(self, *args, **kwargs):
        return reverse_lazy('article:api-article:appurer')

    def getDeltaAppurement(self):
        prorogation = self
        delta_appurement = (prorogation.date_autors_pr + datetime.timedelta(days=30)*prorogation.duree_decdet) - datetime.datetime.now().date()
        return int(delta_appurement.days / 30)

    def getDureeTransfertMax(self):
        prorogation = self
        delta_appurement = (prorogation.date_autors_pr + datetime.timedelta(days=30)*prorogation.duree_decdet) - datetime.datetime.now().date()
        return int(delta_appurement.days / 30)

    def getDecdetStatus(self):
        status_appurement = ''
        nbPending = nbRetard = 0
        for article in self.article_set.all():
            article_status = article.getStatusAppurement()
            if article_status == 'retard':
                nbRetard+=1
            elif article_status == 'pending':
                nbPending+=1
        if nbRetard != 0:
            status_appurement = 'retard'
        elif nbPending !=0:
            status_appurement = 'pending'
        else:
            status_appurement = 'appure'
        return status_appurement

Prorogation/api/views.py
from django.db.models import Q
from rest_framework import generics, permissions
from rest_framework.views import APIView
from rest_framework.response import Response

from Article.models import ArticleModel

from ..models import ProrogationModel
from .serializers import ProrogationListSerializer
from .pagination import ProrogationListPagination

from CSV.CSV import prorogationQuerysetToCSV

class ProrogationDecdetAPIView(APIView):
    def get(self, request, format = None):
        prorogation_args = {}
        prorogation_args['decdet'] = self.request.GET.get('decdet', None)
        prorogation_args['prorogation_mere'] = self.request.GET.get('prorogation_mere', None)
        prorogation_args['code'] = self.request.GET.get('code', None)
        prorogation_args['num_decdet'] = self.request.GET.get('num_decdet', None)
        prorogation_args['importateur'] = self.request.GET.get('importateur', None)
        prorogation_args['declarant'] = self.request.GET.get('declarant', None)
        prorogation_args['val_marchandise'] = self.request.GET.get('val_marchandise', None)
        prorogation_args['taux_suspension'] = self.request.GET.get('taux_suspension', None)
        prorogation_args['montant_dit'] = self.request.GET.get('montant_dit', None)
        prorogation_args['numero_caution'] = self.request.GET.get('numero_caution', None)
        prorogation_args['date_caution'] = self.request.GET.get('date_caution', None)
        prorogation_args['num_contrat'] = self.request.GET.get('num_contrat', None)
        prorogation_args['objet_contrat'] = self.request.GET.get('objet_contrat', None)
        prorogation_args['lieu_execution'] = self.request.GET.get('lieu_execution', None)
        prorogation_args['duree_contrat'] = self.request.GET.get('duree_contrat', None)
        prorogation_args['num_autors_pr'] = self.request.GET.get('num_autors_pr', None)
        prorogation_args['date_autors_pr'] = self.request.GET.get('date_autors_pr', None)
        prorogation_args['duree_decdet'] = self.request.GET.get('duree_decdet', None)
        articlesPks = self.request.GET.get('articlesPks', None)

        prorogation = ProrogationModel.objects.create_prorogation(prorogation_args)
        if prorogation and articlesPks:
            res = ArticleModel.objects.proroger_articles(articlesPks.split(','), prorogation)
            if res:
                return Response({"message" : "Prorogation ajoutée avec succès"}, status = 200)
        return Response({"message" : "Impossible de créer une prorogation avec ces données en entrée"}, status = 400 )


class ProrogationListAPIView(generics.ListAPIView):
    """docstring for DecDetListAPIView."""
    serializer_class    = ProrogationListSerializer
    permission_classes  = [permissions.IsAuthenticated]
    pagination_class    = ProrogationListPagination

    def get_queryset(self, *args, **kwargs):
        decdet_pk = self.kwargs.get('decdet_pk')
        queryset                = ProrogationModel.objects.filter(decdet = decdet_pk).order_by("-timestamp")

        query_code              = self.request.GET.get("code",None)
        query_num_decdet        = self.request.GET.get("num_decdet",None)
        query_appurement        = self.request.GET.get("appurement", None)
        query_importateur       = self.request.GET.get("importateur",None)
        query_declarant         = self.request.GET.get("declarant", None)
        query_taux_suspension   = self.request.GET.get("taux_suspension",None)
        query_numero_caution    = self.request.GET.get("numero_caution", None)
        query_numero_contrat    = self.request.GET.get("numero_contrat", None)
        query_objet_contrat     = self.request.GET.get("objet_contrat", None)
        query_lieu_execution    = self.request.GET.get("lieu_execution", None)
        query_num_autors_pr     = self.request.GET.get("num_autors_pr", None)
        query_year              = self.request.GET.get("year", None)
        query_month             = self.request.GET.get("month", None)

        if query_num_decdet is not None:
            queryset = queryset.filter(Q(num_decdet__icontains = query_num_decdet))
        if query_importateur is not None:
            queryset = queryset.filter(Q(importateur__icontains = query_importateur))
        if query_code is not None:
            queryset = queryset.filter(Q(code = query_code))
        if query_taux_suspension is not None:
            queryset = queryset.filter(Q(taux_suspension = query_taux_suspension))
        if query_declarant is not None:
            queryset = queryset.filter(Q(declarant__icontains = query_declarant))
        if query_objet_contrat is not None:
            queryset = queryset.filter(Q(objet_contrat__icontains = query_objet_contrat))
        if query_lieu_execution is not None:
            queryset = queryset.filter(Q(lieu_execution__icontains = query_lieu_execution))
        if query_numero_caution is not None:
            queryset = queryset.filter(Q(numero_caution__icontains = query_numero_caution))
        if query_num_autors_pr is not None:
            queryset = queryset.filter(Q(num_autors_pr__icontains = query_num_autors_pr))
        if query_year is not None:
            queryset = queryset.filter(Q(date_autors_pr__year = query_year))
        if query_month is not None:
            queryset = queryset.filter(Q(date_autors_pr__month = query_month))
        last_queryset = queryset
        if query_appurement is not None:
            last_queryset = []
            for decdet in queryset:
                if decdet.getDecdetStatus() == query_appurement:
                    last_queryset.append(decdet)
        prorogationQuerysetToCSV(last_queryset)
        return last_queryset

Prorogation/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic

from .forms import ProrogationCreateForm, ProrogationUpdateForm
from .models import ProrogationModel
from DecDet.models import DecDetModel
from Prorogation.models import ProrogationModel
from Transfert.models import TransfertModel
from .api.pagination import PAGE_SIZE


class ProrogationDecdetListView(generic.ListView, LoginRequiredMixin):
    model = ProrogationModel
    template_name = "prorogation_list.html"

    def get_queryset(self, *args, **kwargs):
        queryset = None
        pk = self.kwargs.get('pk')
        try:
            at = DecDetModel.objects.get(pk = pk)
            queryset = at.prorogation_set.all()
        except DecDetModel.DoesNotExist:
            try:
                prorogation = ProrogationModel.objects.get(pk = pk)
                queryset = prorogation.decdet.prorogation_set.all()
            except ProrogationModel.DoesNotExist:
                pass
        return queryset.order_by('-timestamp')

    def get_context_data(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        at = None
        try:
            at = DecDetModel.objects.get(pk = pk)
        except DecDetModel.DoesNotExist:
            try:
                prorogation = ProrogationModel.objects.get(pk = pk)
                at = prorogation.decdet
            except ProrogationModel.DoesNotExist:
                pass
        context = super(ProrogationDecdetListView, self).get_context_data()
        context['decdet']     = at
        context['decdet_api_list_url']    = at.getProrogationApiListUrl()
        context['PAGE_SIZE']              = PAGE_SIZE
        return context


class ProrogationDetailView(generic.DetailView, LoginRequiredMixin):
    model = ProrogationModel
    template_name = "prorogation_detail.html"

    def get_object(self, *args, **kwargs):
        prorogation_pk = self.kwargs.get('pk')
        prorogation = get_object_or_404(ProrogationModel, pk = prorogation_pk)
        return prorogation

    def get_context_data(self, *args, **kwargs):
        prorogation_pk = self.kwargs.get('pk')
        prorogation = self.get_object()
        context = super(ProrogationDetailView, self).get_context_data()
        context['duree_restante_prorogation']  = ProrogationModel.objects.getDureeMaxProrogation(prorogation)
        context['duree_restante_transfert']  = prorogation.getDureeTransfertMax()
        context['date_creation']        = prorogation.timestamp.strftime('%A %d %B %Y')
        context['temps_creation']       = prorogation.timestamp.strftime('%H:%M:%S')
        context['decdet_api_detail_url']= DecDetModel.objects.getApiDetailUrl()
        context['decdet_articles_url']  = prorogation.getArticleListApiUrl()
        context['transfert_article_api_url']  = TransfertModel.objects.getCreateAPIUrl()
        context['prorogation_create_api_url']    = ProrogationModel.objects.getCreateAPIUrl()

        return context


class ProrogationUpdateView(generic.UpdateView, LoginRequiredMixin):
    form_class = ProrogationUpdateForm
    template_name = "prorogation_update.html"

    def get_object(self, *args, **kwargs):
        prorogation_pk = self.kwargs.get('pk')
        prorogation = get_object_or_404(ProrogationModel, pk = prorogation_pk)
        return prorogation

Prorogation/templates/prorogation_filter.html
<label style="float:right">
  <a id="decdet-filter-toggle-btn" href="#" ><i class="fas fa-filter"></i></a>
  Filtres
</label>
<br>
<br>
<form id="decdet-list-filter-form" style="display:none" class="form-filter-decdet">

    <div class='hr'>
        <span class='hr-title'>Déclaration</span>
    </div>

    <div class="row">
      <div class="col-1">
        <label>CODE</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" maxlength="4" name="code" value="">
      </div>
      <div class="col-1">
          <label>N°</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" name="num_decdet" value="">
      </div>
      <div class="col-1">
        <label>Statut</label>
      </div>
      <div class="col-3">
        <select class="form-control" name="appurement">
          <option value="">Sélectionnez un état</option>
          <option value="appure" class="appurement-appure">Appuré</option>
          <option value="pending" class="appurement-pending">En cours</option>
          <option value="retard" class="appurement-retard">En retard</option>
        </select>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-1">
          <label>Importateur</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" name="importateur" value="">
      </div>
      <div class="col-1">
          <label>Déclarant</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" name="declarant" value="">
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-2 offset-3">
        <label>Taux de suspension</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="number"  name="taux_suspension" value="">
      </div>
    </div>

    <div class='hr'>
        <span class='hr-title'>Caution</span>
    </div>

    <div class="row">
      <div class="col-1">
        <label>N° de caution</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="number" name="numero_caution" value="">
      </div>
    </div>

    <div class='hr'>
        <span class='hr-title'>Contrat</span>
    </div>

    <div class="row">
      <div class="col-1">
        <label>N° du contrat</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="number" name="num_contrat" value="">
      </div>
      <div class="col-1">
          <label>Objet du Contrat</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" name="objet_contrat" value="">
      </div>
      <div class="col-1">
          <label>Lieu d'exécution</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" name="lieu_execution" value="">
      </div>
    </div>

    <div class='hr'>
        <span class='hr-title'>Autorisation de Prorogation</span>
    </div>

    <div class="row">
      <div class="col-2">
          <label>N° Autorisation</label>
      </div>
      <div class="col-3">
        <input class="form-control" type="text" name="num_autors_pr" value="">
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-2">
        <label>Date de l'autorisation </label>
      </div>
      <div class="col-3">
        <select class="form-control" name="month" style="width:auto">
          <option class="form-control" value="">Sélectionnez un mois</option>
          <option class="form-control" value="1">Janvier</option>
          <option class="form-control" value="2">Février</option>
          <option class="form-control" value="3">Mars</option>
          <option class="form-control" value="4">Avril</option>
          <option class="form-control" value="5">Mai</option>
          <option class="form-control" value="6">Juin</option>
          <option class="form-control" value="7">Juillet</option>
          <option class="form-control" value="8">Août</option>
          <option class="form-control" value="9">Septembre</option>
          <option class="form-control" value="10">Octobre</option>
          <option class="form-control" value="11">Novembre</option>
          <option class="form-control" value="12">Décembre</option>
        </select>
      </div>
      <div class="col-2">

        <label>Année</label>
      </div>
      <div class="col-4">
        <input class="form-control" type="number" min="1900" name="year">
      </div>

    </div>

    <br>
    <input id="decdet-filter-submit-btn" type="submit" class="btn btn-primary" value="Filtrer">
    <input  type="reset" class="btn btn-secondary" value="Annuler">
</form>
<!-- Must Be Used In DecDet_List including the appropriate script file -->

Prorogation/templates/prorogation_form.html
<form id="prorogation-create-form" method="post">
  {% csrf_token %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        {% if prorogation_depuis_prorogaiton %}
        <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
        <input readonly type="text" name="decdet" value="{{object.decdet.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />

        <label for="id_decdet" class="col-form-label  requiredField"> N° Prorogation mère <span class="asteriskField">*</span></label>
        <input readonly type="text" name="prorogation_mere" value="{{object.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />

        {% else %}
          <label for="id_decdet" class="col-form-label  requiredField"> N° Admission temporaire <span class="asteriskField">*</span></label>
          <input readonly type="text" name="decdet" value="{{object.num_decdet}}" maxlength="4" class="textinput textInput form-control" required id="id_decdet" />
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-6 offset-0">

<br>
        <div class='hr'>
            <span class='hr-title'>Déclaration</span>
        </div>

        <label for="id_code" class="col-form-label  requiredField"> Code <span class="asteriskField">*</span></label>
        <input type="text" name="code" value="" maxlength="4" class="textinput textInput form-control" required id="id_code" />

        <label for="id_num_decdet" class="col-form-label  requiredField"> N° de la déclaration <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_decdet" value="" maxlength="255" class="textinput textInput form-control" required id="id_num_decdet" />


        <label for="id_importateur" class="col-form-label  requiredField"> Importateur <span class="asteriskField">*</span>
        </label>
        <input type="text" name="importateur" value="{{object.importateur}}" maxlength="255" class="textinput textInput form-control" required id="id_importateur" />


        <label for="id_declarant" class="col-form-label  requiredField"> Déclarant <span class="asteriskField">*</span>
        </label>
        <input type="text" name="declarant" value="{{object.declarant}}" maxlength="255" class="textinput textInput form-control" required id="id_declarant" />


        <label for="id_val_marchandise" class="col-form-label  requiredField"> Valeur marchandise <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="val_marchandise" value=""  class="numberinput form-control" required id="id_val_marchandise" />
          <div class="input-group-prepend">
            <div class="input-group-text">DA</div>
          </div>
        </div>


        <label for="id_taux_suspension" class="col-form-label  requiredField"> Taux de suspension <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="taux_suspension" value=""  class="numberinput form-control" required id="id_taux_suspension" />
          <div class="input-group-prepend">
            <div class="input-group-text">%</div>
          </div>
        </div>

        <label for="id_montant_dit" class="col-form-label  requiredField"> Montant D/T <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="montant_dit" value=""  class="numberinput form-control" required id="id_montant_dit" />
          <div class="input-group-prepend">
            <div class="input-group-text">DA</div>
          </div>
        </div>

        <br>
        <div class='hr'>
            <span class='hr-title'>Caution</span>
        </div>

        <label for="id_numero_caution" class="col-form-label  requiredField"> Numéro caution <span class="asteriskField">*</span>
        </label>
        <input type="text" min="0" name="numero_caution" value="{{object.numero_caution}}"  class="textinput form-control" required id="id_numero_caution" />

        <label for="id_date_caution" class="col-form-label  requiredField"> Date de caution <span class="asteriskField">*</span>
        </label>
        <input type="date" name="date_caution" value="{{object.date_caution|date:'Y-m-d'}}"  class="dateinput form-control" required id="id_date_caution" />
        <!--<input type="hidden" name="initial-date_caution"   id="initial-id_date_caution" />-->

      </div>
      <div class="col-6">


<br>
        <div class='hr'>
            <span class='hr-title'>Contrat</span>
        </div>

        <label for="id_num_contrat" class="col-form-label  requiredField"> N° du contrat <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_contrat" value="{{object.num_contrat}}" maxlength="255" class="textinput textInput form-control" required id="id_num_contrat" />


        <label for="id_objet_contrat" class="col-form-label  requiredField"> Objet du contrat <span class="asteriskField">*</span>
        </label>
        <input type="text" name="objet_contrat" value="{{object.objet_contrat}}" maxlength="255" class="textinput textInput form-control" required id="id_objet_contrat" />

        <label for="id_lieu_execution" class="col-form-label  requiredField"> Lieu d'exécution <span class="asteriskField">*</span>
        </label>
        <input type="text" name="lieu_execution" value="{{object.lieu_execution}}" maxlength="255" class="textinput textInput form-control" required id="id_lieu_execution" />

        <label for="id_duree_contrat" class="col-form-label  requiredField"> Durée du contrat <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="duree_contrat" value="{{object.duree_contrat}}"  class="numberinput form-control" required id="id_duree_contrat" />
          <div class="input-group-prepend">
            <div class="input-group-text">mois</div>
          </div>
        </div>

<br>
        <div class='hr'>
            <span class='hr-title'>Autorisation de prorogation</span>
        </div>

        <label for="id_num_autors_pr" class="col-form-label  requiredField"> N° de l'autorisation de prorogation <span class="asteriskField">*</span>
        </label>
        <input type="text" name="num_autors_pr" value="" maxlength="255" class="textinput textInput form-control" required id="id_num_autors_pr" />



        <label for="id_date_autors_pr" class="col-form-label  requiredField"> Date de l'autorisation de prorogation <span class="asteriskField">*</span>
        </label>
        <input type="date" name="date_autors_pr" value=""  class="dateinput form-control" required id="id_date_autors_pr" />

        <label for="id_duree_decdet" class="col-form-label  requiredField"> Durée accordée <span class="asteriskField">*</span>
        </label>
        <div class="input-group">
          <input type="number" min="0" name="duree_decdet" value=""  class="numberinput form-control" required id="id_duree_decdet" />
          <div class="input-group-prepend">
            <div class="input-group-text">mois</div>
          </div>
        </div>



      </div>
    </div>
  </div>
    <br>
    <input hidden type="submit">
</form>

Prorogation/templates/prorogation_form_modal.html
{% load mathfilters %}



<div class="modal fade" id="prorogation-create-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Prorogation depuis : {{object}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {% include "prorogation_form.html" with object=object prorogation_depuis_prorogaiton=prorogation_depuis_prorogaiton %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <label>La durée maximale à accorder est de </label>
            <strong>{{duree_max}} mois</strong> <br>
            <label> pour ne pas dépasser le contrat</label>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <button id="prorogation-create-form-submit-btn"  type="button" class="btn btn-primary">Ajouter</button>
      </div>
    </div>
  </div>
</div>